# Molecules

Molecule records may be retrieved in a number of ways, such as lookup of single molecules using various identifiers or searching for compounds via similarity.

## Get a single molecule by ChEMBL id

All the main entities in the ChEMBL database have a ChEMBL ID. It is a stable identifier designed for straightforward lookup of data.

## Get many molecules by id

In [105]:
chembl_ids = [
    'CHEMBL2108700',
    'CHEMBL253582',
    'CHEMBL344637',
    'CHEMBL689',
    'CHEMBL604608',
    'CHEMBL539',
    'CHEMBL575060',
    'CHEMBL1261',
    'CHEMBL196',
    'CHEMBL541',
    'CHEMBL2108751',
    'CHEMBL1909054',
    'CHEMBL2108814',
    'CHEMBL2107951',
    'CHEMBL1201646',
    'CHEMBL2107529',
    'CHEMBL171679',
    'CHEMBL444122',
    'CHEMBL1187',
    'CHEMBL186314',
    'CHEMBL2107798',
    'CHEMBL2108744',
    'CHEMBL2108264',
    'CHEMBL2108215',
    'CHEMBL2108866',
    'CHEMBL2108075',
    'CHEMBL288114',
    'CHEMBL1200731',
    'CHEMBL1909054',
    'CHEMBL2106111'
]

In [119]:
from chembl_webresource_client.new_client import new_client

molecule = new_client.molecule
mols = molecule.filter(molecule_chembl_id__in=chembl_ids)
display(len(mols))
df = pd.DataFrame(mols)
df.to_csv('chembl.csv', index=False)

29

In [120]:
df.columns

Index(['atc_classifications', 'availability_type', 'biotherapeutic',
       'black_box_warning', 'chebi_par_id', 'chirality', 'cross_references',
       'dosed_ingredient', 'first_approval', 'first_in_class', 'helm_notation',
       'indication_class', 'inorganic_flag', 'max_phase', 'molecule_chembl_id',
       'molecule_hierarchy', 'molecule_properties', 'molecule_structures',
       'molecule_synonyms', 'molecule_type', 'natural_product', 'oral',
       'parenteral', 'polymer_flag', 'pref_name', 'prodrug', 'structure_type',
       'therapeutic_flag', 'topical', 'usan_stem', 'usan_stem_definition',
       'usan_substem', 'usan_year', 'withdrawn_class', 'withdrawn_country',
       'withdrawn_flag', 'withdrawn_reason', 'withdrawn_year'],
      dtype='object')

In [129]:
print(df['cross_references'][0][0])

{'xref_id': 'acetic%20acid,%20glacial', 'xref_name': 'acetic acid, glacial', 'xref_src': 'DailyMed'}

In [131]:
print(df['molecule_hierarchy'][0])

{'molecule_chembl_id': 'CHEMBL539', 'parent_chembl_id': 'CHEMBL539'}

In [136]:
display(df['molecule_properties'][0])

{'alogp': '0.09',
 'aromatic_rings': 0,
 'cx_logd': '-3.00',
 'cx_logp': '-0.22',
 'cx_most_apka': '4.54',
 'cx_most_bpka': None,
 'full_molformula': 'C2H4O2',
 'full_mwt': '60.05',
 'hba': 1,
 'hba_lipinski': 2,
 'hbd': 1,
 'hbd_lipinski': 1,
 'heavy_atoms': 4,
 'molecular_species': 'ACID',
 'mw_freebase': '60.05',
 'mw_monoisotopic': '60.0211',
 'num_lipinski_ro5_violations': 0,
 'num_ro5_violations': 0,
 'psa': '37.30',
 'qed_weighted': '0.43',
 'ro3_pass': 'Y',
 'rtb': 0}

In [135]:
print(df['molecule_synonyms'][1][0])

{'molecule_synonym': 'Acidum benzoicum', 'syn_type': 'OTHER', 'synonyms': 'ACIDUM BENZOICUM'}

## Find compounds similar to given SMILES query with similarity threshold of 70%

In [8]:
from chembl_webresource_client.new_client import new_client

similarity = new_client.similarity
res = similarity.filter(smiles="CO[C@@H](CCC#C\C=C/CCCC(C)CCCCC=C)C(=O)[O-]", similarity=70).only(['molecule_chembl_id', 'similarity'])
for i in res:
    print(i)
    
pd.DataFrame(res)

{'molecule_chembl_id': 'CHEMBL477889', 'similarity': '85.4166686534881591796875'}
{'molecule_chembl_id': 'CHEMBL478779', 'similarity': '85.4166686534881591796875'}
{'molecule_chembl_id': 'CHEMBL477888', 'similarity': '85.4166686534881591796875'}
{'molecule_chembl_id': 'CHEMBL2304268', 'similarity': '70.1754391193389892578125'}

  molecule_chembl_id                 similarity
0       CHEMBL477889  85.4166686534881591796875
1       CHEMBL478779  85.4166686534881591796875
2       CHEMBL477888  85.4166686534881591796875
3      CHEMBL2304268  70.1754391193389892578125

## Find compounds similar to aspirin (CHEMBL25) with similarity threshold of 70%

In [9]:
from chembl_webresource_client.new_client import new_client

similarity = new_client.similarity
res = similarity.filter(chembl_id='CHEMBL25', similarity=70).only(['molecule_chembl_id', 'pref_name', 'similarity'])
display(res)
pd.DataFrame(res)

[{'molecule_chembl_id': 'CHEMBL1697753', 'pref_name': 'ASPIRIN DL-LYSINE', 'similarity': '100'}, {'molecule_chembl_id': 'CHEMBL2296002', 'pref_name': None, 'similarity': '100'}, {'molecule_chembl_id': 'CHEMBL3833325', 'pref_name': 'CARBASPIRIN CALCIUM', 'similarity': '88.8888895511627197265625'}, {'molecule_chembl_id': 'CHEMBL3833404', 'pref_name': 'CARBASPIRIN', 'similarity': '88.8888895511627197265625'}, '...(remaining elements truncated)...']

  molecule_chembl_id            pref_name                 similarity
0      CHEMBL1697753    ASPIRIN DL-LYSINE                        100
1      CHEMBL2296002                 None                        100
2      CHEMBL3833325  CARBASPIRIN CALCIUM  88.8888895511627197265625
3      CHEMBL3833404          CARBASPIRIN  88.8888895511627197265625
4       CHEMBL350343       DIPLOSALSALATE  85.7142865657806396484375
5      CHEMBL4515737                 None  70.3703701496124267578125
6      CHEMBL1451173          DIPYROCETYL  69.9999988079071044921875

## Find compounds with the same connectivity

In [10]:
from chembl_webresource_client.new_client import new_client

molecule = new_client.molecule
res = molecule.filter(molecule_structures__canonical_smiles__connectivity='CN(C)C(=N)N=C(N)N').only(['molecule_chembl_id', 'pref_name'])
for i in res:
    print(i)
pd.DataFrame(res)

{'molecule_chembl_id': 'CHEMBL1431', 'pref_name': 'METFORMIN'}
{'molecule_chembl_id': 'CHEMBL1703', 'pref_name': 'METFORMIN HYDROCHLORIDE'}
{'molecule_chembl_id': 'CHEMBL3094198', 'pref_name': None}

  molecule_chembl_id                pref_name
0         CHEMBL1431                METFORMIN
1         CHEMBL1703  METFORMIN HYDROCHLORIDE
2      CHEMBL3094198                     None

## Get molecules with molecular weight <= 300

In [21]:
from chembl_webresource_client.new_client import new_client

molecule = new_client.molecule
light_molecules = molecule.filter(molecule_properties__mw_freebase__lte=300)

print(len(light_molecules))
print(light_molecules)
#d = pd.DataFrame(light_molecules)
#d.head(1)

416958
[{'atc_classifications': [], 'availability_type': -1, 'biotherapeutic': None, 'black_box_warning': 0, 'chebi_par_id': None, 'chirality': -1, 'cross_references': [], 'dosed_ingredient': False, 'first_approval': None, 'first_in_class': -1, 'helm_notation': None, 'indication_class': None, 'inorganic_flag': -1, 'max_phase': 0, 'molecule_chembl_id': 'CHEMBL269758', 'molecule_hierarchy': {'molecule_chembl_id': 'CHEMBL269758', 'parent_chembl_id': 'CHEMBL269758'}, 'molecule_properties': {'alogp': '3.78', 'aromatic_rings': 2, 'cx_logd': '3.50', 'cx_logp': '3.50', 'cx_most_apka': None, 'cx_most_bpka': None, 'full_molformula': 'C18H14O2', 'full_mwt': '262.31', 'hba': 2, 'hba_lipinski': 2, 'hbd': 0, 'hbd_lipinski': 0, 'heavy_atoms': 20, 'molecular_species': 'NEUTRAL', 'mw_freebase': '262.31', 'mw_monoisotopic': '262.0994', 'num_lipinski_ro5_violations': 0, 'num_ro5_violations': 0, 'psa': '26.30', 'qed_weighted': '0.58', 'ro3_pass': 'N', 'rtb': 1}, 'molecule_structures': {'canonical_smiles': 'C#C/C=C1\\CCC(c2cccc3ccccc23)C(=O)O1', 'molfile': '\n     RDKit          2D\n\n 20 22  0  0  0  0  0  0  0  0999 V2000\n    3.4042   -4.0667    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.4042   -3.4667    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.8792   -4.3667    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    3.9250   -3.1625    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.9250   -2.5625    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    1.3292   -4.0625    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.3667   -4.0667    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.8042   -3.7625    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.8792   -3.1667    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.9250   -4.3667    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    1.8500   -4.3625    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.4417   -2.2542    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    2.3667   -3.4667    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.4417   -3.4542    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.4042   -2.2625    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.9667   -3.1542    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.9667   -2.5542    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.4417   -1.6542    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.4042   -1.6625    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.9250   -1.3625    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  2  1  1  0\n  3  1  1  0\n  4  2  1  0\n  5  4  1  0\n  6 11  1  0\n  7  3  1  0\n  8  6  3  0\n  9  2  1  0\n 10  1  2  0\n 11  7  2  0\n 12  5  2  0\n 13  7  1  0\n 14  4  2  0\n 15  5  1  0\n 16 14  1  0\n 17 16  2  0\n 18 12  1  0\n 19 15  2  0\n 20 19  1  0\n 13  9  1  0\n 17 12  1  0\n 18 20  2  0\nM  END\n\n> <chembl_id>\nCHEMBL269758\n\n> <chembl_pref_name>\nNone\n\n', 'standard_inchi': 'InChI=1S/C18H14O2/c1-2-6-14-11-12-17(18(19)20-14)16-10-5-8-13-7-3-4-9-15(13)16/h1,3-10,17H,11-12H2/b14-6+', 'standard_inchi_key': 'NHOIHEBFAKOZIE-MKMNVTDBSA-N'}, 'molecule_synonyms': [], 'molecule_type': 'Small molecule', 'natural_product': -1, 'oral': False, 'parenteral': False, 'polymer_flag': 0, 'pref_name': None, 'prodrug': -1, 'structure_type': 'MOL', 'therapeutic_flag': False, 'topical': False, 'usan_stem': None, 'usan_stem_definition': None, 'usan_substem': None, 'usan_year': None, 'withdrawn_class': None, 'withdrawn_country': None, 'withdrawn_flag': False, 'withdrawn_reason': None, 'withdrawn_year': None}, {'atc_classifications': [], 'availability_type': -1, 'biotherapeutic': None, 'black_box_warning': 0, 'chebi_par_id': None, 'chirality': -1, 'cross_references': [], 'dosed_ingredient': False, 'first_approval': None, 'first_in_class': -1, 'helm_notation': None, 'indication_class': None, 'inorganic_flag': -1, 'max_phase': 0, 'molecule_chembl_id': 'CHEMBL268365', 'molecule_hierarchy': {'molecule_chembl_id': 'CHEMBL268365', 'parent_chembl_id': 'CHEMBL268365'}, 'molecule_properties': {'alogp': '1.15', 'aromatic_rings': 3, 'cx_logd': '1.46', 'cx_logp': '2.51', 'cx_most_apka': '6.33', 'cx_most_bpka': None, 'full_molformula': 'C16H11N3O3', 'full_mwt': '293.28', 'hba': 5, 'hba_lipinski': 6, 'hbd': 1, 'hbd_lipinski': 1, 'heavy_atoms': 22, 'molecular_species': 'ACID', 'mw_freebase': '293.28', 'mw_monoisotopic': '293.0800', 'num_lipinski_ro5_violations': 0, 'num_ro5_violations': 0, 'psa': '84.82', 'qed_weighted': '0.73', 'ro3_pass': 'N', 'rtb': 3}, 'molecule_structures': {'canonical_smiles': 'O=C(c1ccccc1)c1ccc(-n2ncc(=O)[nH]c2=O)cc1', 'molfile': '\n     RDKit          2D\n\n 22 24  0  0  0  0  0  0  0  0999 V2000\n    6.3417   -2.4250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    6.8542   -2.7250    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    6.3417   -1.8250    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    7.3750   -2.4250    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    7.3750   -1.8250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    6.8542   -1.5250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    6.8500   -5.1167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    6.8542   -3.3250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.8167   -2.7167    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    6.8500   -4.5167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    6.8542   -0.9250    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    6.3292   -5.4167    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    7.3667   -5.4167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    7.3667   -3.6167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    6.3292   -3.6167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    6.3292   -4.2167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    7.3667   -4.2167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    7.3667   -6.0167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    7.8792   -5.1167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    8.4042   -5.4167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    7.8875   -6.3167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    8.4042   -6.0167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  2  1  1  0\n  3  1  1  0\n  4  2  1  0\n  5  6  1  0\n  6  3  1  0\n  7 10  1  0\n  8  2  1  0\n  9  1  2  0\n 10 16  2  0\n 11  6  2  0\n 12  7  2  0\n 13  7  1  0\n 14  8  1  0\n 15  8  2  0\n 16 15  1  0\n 17 14  2  0\n 18 13  2  0\n 19 13  1  0\n 20 19  2  0\n 21 18  1  0\n 22 20  1  0\n  4  5  2  0\n 10 17  1  0\n 21 22  2  0\nM  END\n\n> <chembl_id>\nCHEMBL268365\n\n> <chembl_pref_name>\nNone\n\n', 'standard_inchi': 'InChI=1S/C16H11N3O3/c20-14-10-17-19(16(22)18-14)13-8-6-12(7-9-13)15(21)11-4-2-1-3-5-11/h1-10H,(H,18,20,22)', 'standard_inchi_key': 'KXRCWAXGSZBUMP-UHFFFAOYSA-N'}, 'molecule_synonyms': [], 'molecule_type': 'Small molecule', 'natural_product': -1, 'oral': False, 'parenteral': False, 'polymer_flag': 0, 'pref_name': None, 'prodrug': -1, 'structure_type': 'MOL', 'therapeutic_flag': False, 'topical': False, 'usan_stem': None, 'usan_stem_definition': None, 'usan_substem': None, 'usan_year': None, 'withdrawn_class': None, 'withdrawn_country': None, 'withdrawn_flag': False, 'withdrawn_reason': None, 'withdrawn_year': None}, {'atc_classifications': [], 'availability_type': -1, 'biotherapeutic': None, 'black_box_warning': 0, 'chebi_par_id': None, 'chirality': -1, 'cross_references': [], 'dosed_ingredient': False, 'first_approval': None, 'first_in_class': -1, 'helm_notation': None, 'indication_class': None, 'inorganic_flag': -1, 'max_phase': 0, 'molecule_chembl_id': 'CHEMBL415286', 'molecule_hierarchy': {'molecule_chembl_id': 'CHEMBL415286', 'parent_chembl_id': 'CHEMBL415286'}, 'molecule_properties': {'alogp': '1.21', 'aromatic_rings': 3, 'cx_logd': '1.37', 'cx_logp': '2.42', 'cx_most_apka': '6.33', 'cx_most_bpka': None, 'full_molformula': 'C14H9N3O3S', 'full_mwt': '299.31', 'hba': 6, 'hba_lipinski': 6, 'hbd': 1, 'hbd_lipinski': 1, 'heavy_atoms': 21, 'molecular_species': 'ACID', 'mw_freebase': '299.31', 'mw_monoisotopic': '299.0365', 'num_lipinski_ro5_violations': 0, 'num_ro5_violations': 0, 'psa': '84.82', 'qed_weighted': '0.74', 'ro3_pass': 'N', 'rtb': 3}, 'molecule_structures': {'canonical_smiles': 'O=C(c1ccc(-n2ncc(=O)[nH]c2=O)cc1)c1cccs1', 'molfile': '\n     RDKit          2D\n\n 21 23  0  0  0  0  0  0  0  0999 V2000\n    3.8042   -1.6000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.3167   -1.9000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    3.8042   -1.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    4.8417   -1.6000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    4.8417   -1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.3167   -0.7000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.8375   -4.5917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.3167   -4.2917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.3792   -4.3500    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0\n    4.3167   -2.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.2875   -1.8917    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    4.3167   -3.6917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.9000   -5.2000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.7792   -4.8000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.7917   -4.5917    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    4.3167   -0.0917    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    5.4792   -5.3167    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.8375   -2.7917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.8000   -2.7917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.7917   -3.3917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.8375   -3.3917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  2  1  1  0\n  3  1  1  0\n  4  2  1  0\n  5  6  1  0\n  6  3  1  0\n  7  8  1  0\n  8 12  1  0\n  9  7  1  0\n 10  2  1  0\n 11  1  2  0\n 12 20  2  0\n 13  7  2  0\n 14  9  1  0\n 15  8  2  0\n 16  6  2  0\n 17 13  1  0\n 18 10  1  0\n 19 10  2  0\n 20 19  1  0\n 21 18  2  0\n  4  5  2  0\n 21 12  1  0\n 17 14  2  0\nM  END\n\n> <chembl_id>\nCHEMBL415286\n\n> <chembl_pref_name>\nNone\n\n', 'standard_inchi': 'InChI=1S/C14H9N3O3S/c18-12-8-15-17(14(20)16-12)10-5-3-9(4-6-10)13(19)11-2-1-7-21-11/h1-8H,(H,16,18,20)', 'standard_inchi_key': 'RJEKIHQABSVVMV-UHFFFAOYSA-N'}, 'molecule_synonyms': [], 'molecule_type': 'Small molecule', 'natural_product': -1, 'oral': False, 'parenteral': False, 'polymer_flag': 0, 'pref_name': None, 'prodrug': -1, 'structure_type': 'MOL', 'therapeutic_flag': False, 'topical': False, 'usan_stem': None, 'usan_stem_definition': None, 'usan_substem': None, 'usan_year': None, 'withdrawn_class': None, 'withdrawn_country': None, 'withdrawn_flag': False, 'withdrawn_reason': None, 'withdrawn_year': None}, {'atc_classifications': [], 'availability_type': -1, 'biotherapeutic': None, 'black_box_warning': 0, 'chebi_par_id': None, 'chirality': -1, 'cross_references': [], 'dosed_ingredient': False, 'first_approval': None, 'first_in_class': -1, 'helm_notation': None, 'indication_class': None, 'inorganic_flag': -1, 'max_phase': 0, 'molecule_chembl_id': 'CHEMBL6226', 'molecule_hierarchy': {'molecule_chembl_id': 'CHEMBL6226', 'parent_chembl_id': 'CHEMBL6226'}, 'molecule_properties': {'alogp': '1.82', 'aromatic_rings': 3, 'cx_logd': '2.60', 'cx_logp': '3.65', 'cx_most_apka': '6.33', 'cx_most_bpka': None, 'full_molformula': 'C17H15N3O2', 'full_mwt': '293.33', 'hba': 4, 'hba_lipinski': 5, 'hbd': 1, 'hbd_lipinski': 1, 'heavy_atoms': 22, 'molecular_species': 'ACID', 'mw_freebase': '293.33', 'mw_monoisotopic': '293.1164', 'num_lipinski_ro5_violations': 0, 'num_ro5_violations': 0, 'psa': '67.75', 'qed_weighted': '0.80', 'ro3_pass': 'N', 'rtb': 3}, 'molecule_structures': {'canonical_smiles': 'Cc1cc(-n2ncc(=O)[nH]c2=O)ccc1Cc1ccccc1', 'molfile': '\n     RDKit          2D\n\n 22 24  0  0  0  0  0  0  0  0999 V2000\n    3.8042   -1.6000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.3167   -1.9000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    3.8042   -1.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    4.8417   -1.6000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0\n    4.8417   -1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.3167   -0.7000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.3167   -2.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.8000   -2.7917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.3167   -3.6917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.7917   -3.3917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.2875   -1.8917    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    4.8375   -2.7917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.3167   -4.2917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.3167   -0.0917    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0\n    4.8375   -3.3917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.8375   -4.5917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    3.2750   -3.6917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.3500   -4.2917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    4.8292   -5.1917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.3542   -5.4917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.8667   -4.5917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    5.8667   -5.1917    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n  2  1  1  0\n  3  1  1  0\n  4  2  1  0\n  5  6  1  0\n  6  3  1  0\n  7  2  1  0\n  8  7  2  0\n  9 15  1  0\n 10  8  1  0\n 11  1  2  0\n 12  7  1  0\n 13  9  1  0\n 14  6  2  0\n 15 12  2  0\n 16 13  1  0\n 17 10  1  0\n 18 16  1  0\n 19 16  2  0\n 20 19  1  0\n 21 18  2  0\n 22 20  2  0\n  4  5  2  0\n 10  9  2  0\n 21 22  1  0\nM  END\n\n> <chembl_id>\nCHEMBL6226\n\n> <chembl_pref_name>\nNone\n\n', 'standard_inchi': 'InChI=1S/C17H15N3O2/c1-12-9-15(20-17(22)19-16(21)11-18-20)8-7-14(12)10-13-5-3-2-4-6-13/h2-9,11H,10H2,1H3,(H,19,21,22)', 'standard_inchi_key': 'NRBLBHBWDRKIIY-UHFFFAOYSA-N'}, 'molecule_synonyms': [], 'molecule_type': 'Small molecule', 'natural_product': -1, 'oral': False, 'parenteral': False, 'polymer_flag': 0, 'pref_name': None, 'prodrug': -1, 'structure_type': 'MOL', 'therapeutic_flag': False, 'topical': False, 'usan_stem': None, 'usan_stem_definition': None, 'usan_substem': None, 'usan_year': None, 'withdrawn_class': None, 'withdrawn_country': None, 'withdrawn_flag': False, 'withdrawn_reason': None, 'withdrawn_year': None}, '...(remaining elements truncated)...']

## Get molecules with molecular weight <= 300 AND pref_name ending with nib

In [24]:
from chembl_webresource_client.new_client import new_client

molecule = new_client.molecule
light_nib_molecules = molecule.filter(molecule_properties__mw_freebase__lte=300, pref_name__iendswith="nib").only(['molecule_chembl_id', 'pref_name'])

d = pd.DataFrame(light_nib_molecules)
d

  molecule_chembl_id     pref_name
0       CHEMBL276711     SEMAXANIB
1      CHEMBL4594348  ELSUBRUTINIB