In [17]:
import requests
import pandas as pd
import io

In [45]:
compound_names = ['glucose', 'sucrose', 'D-glucitol', 'mannitol', 'fructose',
'acetic acid', 'glutamic acid', 'citric acid', 'L-ascorbic acid', 'benzoic acid',
'pectin', 'carboxymethylcellulose', 'gum arabic', 'xanthan',
'Maltodextrin-dextrose equivalent 10-15', 'fructooligosaccharide', 'inulin', 'sucralose',
'aspartame', 'stevioside', 'stevia', 'phosphoric acid',
'sodium carbonate', 'Dioleoyl lecithin', 'alginate', 'carrageenan',
'agar', 'Amylum', 'Papain Inhibitor', 'gallic acid',
'potassium chloride', 'carboxymethylcellulose', 'calcium nitrate']


#compound_str = compound_names.join('')
compound_str = '%7C'.join(compound_names)
compound_str = compound_str.replace(' ', '%20')
compound_str

'glucose%7Csucrose%7CD-glucitol%7Cmannitol%7Cfructose%7Cacetic%20acid%7Cglutamic%20acid%7Ccitric%20acid%7CL-ascorbic%20acid%7Cbenzoic%20acid%7Cpectin%7Ccarboxymethylcellulose%7Cgum%20arabic%7Cxanthan%7CMaltodextrin-dextrose%20equivalent%2010-15%7Cfructooligosaccharide%7Cinulin%7Csucralose%7Caspartame%7Cstevioside%7Cstevia%7Cphosphoric%20acid%7Csodium%20carbonate%7CDioleoyl%20lecithin%7Calginate%7Ccarrageenan%7Cagar%7CAmylum%7CPapain%20Inhibitor%7Cgallic%20acid%7Cpotassium%20chloride%7Ccarboxymethylcellulose%7Ccalcium%20nitrate'

In [52]:
base_url = 'https://chem.nlm.nih.gov/api/data/name/inlist'
data = 'complete'
out_format = 'json'  # tsv json
api_url = f"{base_url}/{compound_str}?data={data}&format={out_format}"
print(api_url)
response = requests.get(api_url)
response.json()

https://chem.nlm.nih.gov/api/data/name/inlist/glucose%7Csucrose%7CD-glucitol%7Cmannitol%7Cfructose%7Cacetic%20acid%7Cglutamic%20acid%7Ccitric%20acid%7CL-ascorbic%20acid%7Cbenzoic%20acid%7Cpectin%7Ccarboxymethylcellulose%7Cgum%20arabic%7Cxanthan%7CMaltodextrin-dextrose%20equivalent%2010-15%7Cfructooligosaccharide%7Cinulin%7Csucralose%7Caspartame%7Cstevioside%7Cstevia%7Cphosphoric%20acid%7Csodium%20carbonate%7CDioleoyl%20lecithin%7Calginate%7Ccarrageenan%7Cagar%7CAmylum%7CPapain%20Inhibitor%7Cgallic%20acid%7Cpotassium%20chloride%7Ccarboxymethylcellulose%7Ccalcium%20nitrate?data=complete&format=json

{'total': 40,
 'start': 1,
 'end': 25,
 'results': [{'id': '0000050704',
   'lastMod': 1663885675000,
   'summary': {'u': 'rn/eq/50-70-4',
    'na': 'Sorbitol [USP:NF]',
    'rn': '50-70-4',
    'ik': 'FBPFZTCFMRRESA-JGWLITMVSA-N',
    'f': 'C6-H14-O6',
    'w': 182.171,
    '3d': True,
    'mh': 'Sorbitol',
    'ci': 20337},
   'notes': [{'t': 211,
     'e': [{'d': 'A polyhydric alcohol with about half the sweetness of sucrose. Sorbitol occurs naturally and is also produced synthetically from glucose. It was formerly used as a diuretic and may still be used as a laxative and in irrigating solutions for some surgical procedures. It is also used in many manufacturing processes, as a pharmaceutical aid, and in several research applications.',
       's': ['MeSH']}]}],
   'categories': [{'t': 386,
     'e': [{'d': 'Antiviral (COVID-19)', 's': ['PubMed']},
      {'d': 'Cathartics', 's': ['MeSH', 'SIS']},
      {'d': 'Flavoring Agents', 's': ['SIS']},
      {'d': 'Food Additives', 's': ['SIS']},
      {'d': 'Gastrointestinal Agents', 's': ['SIS']},
      {'d': 'Human Data', 's': ['RTECS']},
      {'d': 'Indicators and Reagents', 's': ['MeSH', 'SIS']},
      {'d': 'Mutation Data', 's': ['RTECS']},
      {'d': 'Pharmaceutic Aid (Flavor)', 's': ['USPDDN']},
      {'d': 'Pharmaceutic Aid (Tablet Excipient)', 's': ['USPDDN']},
      {'d': 'Sweetening Agents', 's': ['MeSH', 'SIS']}]}],
   'numbers': [{'t': 261, 'e': [{'d': '50-70-4', 's': ['PubMed Toxicology']}]},
    {'t': 102, 'e': [{'d': '506T60A25R', 's': ['FDA SRS']}]},
    {'t': 610,
     'e': [{'d': '15060-73-8', 's': ['NLM']},
      {'d': '36134-87-9', 's': ['RTECS']},
      {'d': '3959-53-3', 's': ['NLM']},
      {'d': '63800-20-4', 's': ['RTECS']},
      {'d': '75398-79-7', 's': ['NLM']},
      {'d': '8013-15-8', 's': ['NLM']},
      {'d': '8014-89-9', 's': ['NLM']},
      {'d': '8036-93-9', 's': ['NLM']},
      {'d': '8042-39-5', 's': ['NLM']},
      {'d': '8045-74-7', 's': ['NLM']},
      {'d': '8046-05-7', 's': ['NLM']},
      {'d': '952319-42-5', 's': ['TSCAINV']},
      {'d': '98201-93-5', 's': ['NLM']}]},
    {'t': 611, 'e': [{'d': '0000050704'}]}],
   'names': [{'t': 290,
     'e': [{'d': 'D-Glucitol', 's': ['CTFA']},
      {'d': 'D-Sorbitol', 's': ['HSDB']},
      {'d': 'Sorbitol', 's': ['CTFA', 'MeSH']},
      {'d': 'Sorbitol [USP:NF]', 's': ['NLM', 'USPDDN']}]},
    {'t': 251, 'e': [{'d': 'Sorbitol', 's': ['MeSH']}]},
    {'t': 616,
     'e': [{'d': '(-)-Sorbitol', 's': ['NLM']},
      {'d': 'AI3-19424', 's': ['NLM']},
      {'d': 'CCRIS 1898', 's': ['CCRIS']},
      {'d': 'Cholaxine', 's': ['HSDB', 'RTECS']},
      {'d': 'D-(-)-Sorbitol', 's': ['NLM']},
      {'d': 'D-1,2,3,4,5,6-Hexanehexol', 's': ['NLM']},
      {'d': 'D-Glucitol', 's': ['HSDB', 'RTECS']},
      {'d': 'D-Sorbite', 's': ['HSDB']},
      {'d': 'D-Sorbitol', 's': ['RTECS']},
      {'d': 'D-Sorbol', 's': ['HSDB']},
      {'d': 'Diakarmon', 's': ['HSDB', 'RTECS']},
      {'d': 'EINECS 200-061-5', 's': ['EINECS']},
      {'d': 'Esasorb', 's': ['HSDB']},
      {'d': 'FEMA No. 3029', 's': ['NLM']},
      {'d': 'Foodol D 70', 's': ['NLM']},
      {'d': 'Glucarine', 's': ['NLM']},
      {'d': 'Glucitol', 's': ['HSDB', 'MeSH']},
      {'d': 'Gulitol', 's': ['HSDB', 'RTECS']},
      {'d': 'Hexahydric alcohol', 's': ['HSDB']},
      {'d': 'HSDB 801', 's': ['HSDB']},
      {'d': 'Karion', 's': ['HSDB', 'RTECS']},
      {'d': 'Karion (carbohydrate)', 's': ['NLM']},
      {'d': 'Karion instant', 's': ['NLM']},
      {'d': 'L-Gulitol', 's': ['HSDB', 'RTECS']},
      {'d': 'Medevac', 's': ['MeSH']},
      {'d': 'Multitol', 's': ['NLM']},
      {'d': 'Neosorb', 's': ['HSDB']},
      {'d': 'Neosorb 20/60DC', 's': ['NLM']},
      {'d': 'Neosorb 70/02', 's': ['NLM']},
      {'d': 'Neosorb 70/70', 's': ['NLM']},
      {'d': 'Neosorb P 20/60', 's': ['NLM']},
      {'d': 'Neosorb P 60', 's': ['NLM']},
      {'d': 'Nivitin', 's': ['HSDB', 'RTECS']},
      {'d': 'NSC 25944', 's': ['NLM']},
      {'d': 'Sionit', 's': ['HSDB', 'RTECS']},
      {'d': 'Sionit K', 's': ['NLM']},
      {'d': 'Sionite', 's': ['HSDB']},
      {'d': 'Sionon', 's': ['HSDB', 'RTECS']},
      {'d': 'Siosan', 's': ['HSDB']},
      {'d': 'Sorbex M', 's': ['HSDB']},
      {'d': 'Sorbex R', 's': ['HSDB']},
      {'d': 'Sorbex RP', 's': ['HSDB']},
      {'d': 'Sorbex S', 's': ['HSDB']},
      {'d': 'Sorbex X', 's': ['HSDB']},
      {'d': 'Sorbicolan', 's': ['HSDB', 'RTECS']},
      {'d': 'Sorbilande', 's': ['HSDB']},
      {'d': 'Sorbite', 's': ['RTECS']},
      {'d': 'Sorbitol', 's': ['EPA SRS', 'NLM', 'USPDDN']},
      {'d': 'Sorbitol 3% in plastic container', 's': ['Drugs@FDA']},
      {'d': 'Sorbitol 3.3% in plastic container', 's': ['Drugs@FDA']},
      {'d': 'Sorbitol F', 's': ['NLM']},
      {'d': 'Sorbitol FP', 's': ['NLM']},
      {'d': 'Sorbitol syrup C', 's': ['HSDB']},
      {'d': 'Sorbo', 's': ['RTECS']},
      {'d': 'Sorbol', 's': ['NLM']},
      {'d': 'Sorbostyl', 's': ['HSDB', 'RTECS']},
      {'d': 'Sorvilande', 's': ['HSDB', 'RTECS']},
      {'d': 'UNII-506T60A25R', 's': ['FDA SRS']}]},
    {'t': 614,
     'e': [{'d': 'D-Glucitol',
       's': ['EINECS', 'EPA SRS', 'MeSH', 'TSCAINV', 'USPDDN']},
      {'d': 'D-Sorbitol', 's': ['CCRIS']},
      {'d': 'Glucitol', 's': ['RTECS']}]},
    {'t': 900,
     'e': [{'d': '1,2,3,4,5,6-Hexanehexol', 's': ['GRAS']},
      {'d': 'Glucitol, D-', 's': ['HPV']},
      {'d': 'Sorbitol', 's': ['GRAS', 'INER', 'PAFA']},
      {'d': 'Sorbitol solutions', 's': ['CGB']}]},
    {'t': 294, 'e': [{'d': 'Probilagol', 's': ['MeSH', 'USPDDN']}]}],
   'formulas': [{'t': 608,
     'e': [{'d': 'C6-H14-O6', 's': ['EINECS', 'HSDB', 'RTECS', 'USPDDN']}]}],
   'resources': [{'t': 632,
     'e': [{'d': 'CCRIS', 'u': '50-70-4'},
      {'d': 'ClinicalTrials.gov', 'u': 'sorbitol'},
      {'d': 'DailyMed', 'u': 'Sorbitol'},
      {'d': 'DailyMed Mob', 'u': 'Sorbitol'},
      {'d': 'DrugPortal'},
      {'d': 'GENETOX', 'u': '50-70-4'},
      {'d': 'HSDB', 'u': '801'},
      {'d': 'HSDB Mob', 'u': '801'},
      {'d': 'MedlinePlusAll', 'u': 'Sorbitol'},
      {'d': 'MedlinePlusAll Mob', 'u': 'Sorbitol'},
      {'d': 'MeSH', 'u': 'Sorbitol'},
      {'d': 'MeSH Heading'},
      {'d': 'PubChem'},
      {'d': 'PubMed', 'u': 'Sorbitol+OR+50-70-4+[rn]'},
      {'d': 'PubMed Central'},
      {'d': 'PubMed Central Mob'},
      {'d': 'PubMed Mob', 'u': 'Sorbitol+OR+50-70-4+[rn]'},
      {'d': 'RTECS'}]},
    {'t': 403,
     'e': [{'d': 'CGB'},
      {'d': 'DSL'},
      {'d': 'GRAS',
       'u': 'http://frwebgate.access.gpo.gov/cgi-bin/get-cfr.cgi?TITLE=21&PART=184&SECTION=1835&TYPE=TEXT'},
      {'d': 'HPV'},
      {'d': 'INER'},
      {'d': 'PAFA', 'u': 'SORBITOL'},
      {'d': 'TSCAINV'}]},
    {'t': 999,
     'e': [{'d': 'CAMEO', 'u': '9087'},
      {'d': 'ChEBI'},
      {'d': 'CTD', 'u': 'D013012'},
      {'d': 'DrugBank', 'u': 'DB01638'},
      {'d': 'Drugs@FDA', 'u': 'sorbitol'},
      {'d': 'DSLD', 'u': 'Sorbitol'},
      {'d': 'eChemPortal'},
      {'d': 'EINECS', 'u': '100.000.056'},
      {'d': 'EPA ACToR'},
      {'d': 'EPA CompTox', 'u': 'DTXSID5023588  '},
      {'d': 'EPA Envirofacts',
       'u': 'http://www.epa.gov/enviro/html/emci/chemref/50704.html'},
      {'d': 'EPA PPIS'},
      {'d': 'EPA SRS'},
      {'d': 'FDA SRS', 'u': 'unii/506T60A25R'},
      {'d': 'NIOSH ICSC', 'u': '0892'},
      {'d': 'NIST WebBook'},
      {'d': 'SRC CHEMFATE'},
      {'d': 'SRC DATALOG'},
      {'d': 'USA.gov', 'u': 'Sorbitol'},
      {'d': 'USA.gov Mob', 'u': 'Sorbitol'}]}],
   'toxicityList': [{'o': 'mouse',
     't': 'LD50',
     'r': 'intraperitoneal',
     'd': {'r': 15.0, 'u': 'gm/kg', 'n': 15000.0, 'nu': 'mg/kg'},
     'j': {'t': 'Proceedings of the Society for Experimental Biology and Medicine',
      'v': '35',
      'p': '98',
      'y': '1936'}},
    {'o': 'mouse',
     't': 'LD50',
     'r': 'intravenous',
     'd': {'r': 9480.0, 'u': 'mg/kg'},
     'j': {'t': 'Yakkyoku.  Pharmacy', 'v': '32', 'p': '1367', 'y': '1981'}},
    {'o': 'mouse',
     't': 'LD50',
     'r': 'oral',
     'd': {'r': 17800.0, 'u': 'mg/kg'},
     'j': {'t': 'Yakkyoku.  Pharmacy', 'v': '32', 'p': '1367', 'y': '1981'}},
    {'o': 'mouse',
     't': 'LD50',
     'r': 'subcutaneous',
     'd': {'r': 24.0, 'u': 'gm/kg', 'n': 24000.0, 'nu': 'mg/kg'},
     'j': {'t': 'Drugs in Japan ', 'v': '-', 'p': '607', 'y': '1990'}},
    {'o': 'rat',
     't': 'LD50',
     'r': 'intravenous',
     'd': {'r': 7100.0, 'u': 'mg/kg'},
     'j': {'t': 'FAO Nutrition Meetings Report Series',
      'v': '53A',
      'p': '498',
      'y': '1974'}},
    {'o': 'rat',
     't': 'LD50',
     'r': 'oral',
     'd': {'r': 15900.0, 'u': 'mg/kg'},
     'j': {'t': 'FAO Nutrition Meetings Report Series',
      'v': '53A',
      'p': '498',
      'y': '1974'}},
    {'o': 'rat',
     't': 'LD50',
     'r': 'subcutaneous',
     'd': {'r': 29600.0, 'u': 'mg/kg'},
     'j': {'t': 'Drugs in Japan ', 'v': '-', 'p': '607', 'y': '1990'}},
    {'o': 'women',
     't': 'TDLo',
     'r': 'oral',
     'd': {'r': 1700.0, 'u': 'mg/kg/D', 'nu': 'mg/kg'},
     'e': [{'s': 'GASTROINTESTINAL', 't': '"HYPERMOTILITY, DIARRHEA"'}],
     'j': {'t': 'American Journal of Digestive Diseases',
      'v': '23',
      'p': '568',
      'y': '1978',
      'i': '677114'}}],
   'physicalProps': [{'p': 'Melting Point',
     'd': 11.0,
     'u': 'deg C',
     's': 'EXP'},
    {'p': 'pKa Dissociation Constant', 'd': 13.57, 's': 'EXP'},
    {'p': 'log P (octanol-water)', 'd': -2.2, 's': 'EXP'},
    {'p': 'Water Solubility',
     'd': 2750000.0,
     'u': 'mg/L',
     't': '30',
     's': 'EXP'},
    {'p': 'Vapor Pressure',
     'd': 4.92e-09,
     'u': 'mm Hg',
     't': '25',
     's': 'EST'},
    {'p': "Henry's Law Constant",
     'd': 7.26e-13,
     'u': 'atm-m3/mole',
     't': '25',
     's': 'EST'},
    {'p': 'Atmospheric OH Rate Constant',
     'd': 5e-11,
     'u': 'cm3/molecule-sec',
     't': '25',
     's': 'EST'}],
   'structureDetails': {'w': 182.171,
    'ik': 'FBPFZTCFMRRESA-JGWLITMVSA-N',
    'i': 'InChI=1S/C6H14O6/c7-1-3(9)5(11)6(12)4(10)2-8/h3-12H,1-2H2/t3-,4+,5-,6-/m1/s1',
    's': 'OC[C@@H](O)[C@@H](O)[C@H](O)[C@@H](O)CO',
    'm': '\n  SciTegic09282217562D\n\n 12 11  0  0  0  0            999 V2000\n    0.3552   -0.2069    0.0000 C   0  0  1  0  0  0\n   -0.3552    0.2069    0.0000 C   0  0  1  0  0  0\n    1.0690    0.2069    0.0000 C   0  0  1  0  0  0\n    0.3552   -1.0310    0.0000 O   0  0\n   -1.0690   -0.2069    0.0000 C   0  0  2  0  0  0\n   -0.3552    1.0310    0.0000 O   0  0\n    1.7828   -0.2069    0.0000 C   0  0\n    1.0690    1.0310    0.0000 O   0  0\n   -1.7828    0.2069    0.0000 C   0  0\n   -1.0690   -1.0310    0.0000 O   0  0\n    2.4931    0.2069    0.0000 O   0  0\n   -2.4931   -0.2069    0.0000 O   0  0\n  1  2  1  0\n  1  3  1  0\n  1  4  1  1\n  2  5  1  0\n  2  6  1  1\n  3  7  1  0\n  3  8  1  6\n  5  9  1  0\n  5 10  1  1\n  7 11  1  0\n  9 12  1  0\nM  END\n',
    'm3': '\n  Symyx   06131510363D 1   1.00000     0.00000     0\n\n 26 25  0     0  0            999 V2000\n   -0.0187    1.5258    0.0104 C   0  0  1  0  0  0           0  0  0\n    0.0021   -0.0041    0.0020 C   0  0  1  0  0  0           0  0  0\n    1.4167    2.0553   -0.0004 C   0  0  1  0  0  0           0  0  0\n   -0.7098    1.9991   -1.1473 O   0  0  0  0  0  0           0  0  0\n   -1.4290   -0.5329   -0.1129 C   0  0  2  0  0  0           0  0  0\n    0.7707   -0.4639   -1.1115 O   0  0  0  0  0  0           0  0  0\n    1.3960    3.5852    0.0080 C   0  0  0  0  0  0           0  0  0\n    2.1079    1.5820    1.1573 O   0  0  0  0  0  0           0  0  0\n   -1.4004   -2.0568   -0.2468 C   0  0  0  0  0  0           0  0  0\n   -2.0556    0.0348   -1.2649 O   0  0  0  0  0  0           0  0  0\n    2.7303    4.0804   -0.1195 O   0  0  0  0  0  0           0  0  0\n   -2.7375   -2.5610   -0.2370 O   0  0  0  0  0  0           0  0  0\n   -0.5289    1.8773    0.9072 H   0  0  0  0  0  0           0  0  0\n    0.4501   -0.3665    0.9272 H   0  0  0  0  0  0           0  0  0\n    1.9269    1.7038   -0.8972 H   0  0  0  0  0  0           0  0  0\n   -0.2271    1.6667   -1.9164 H   0  0  0  0  0  0           0  0  0\n   -1.9910   -0.2570    0.7794 H   0  0  0  0  0  0           0  0  0\n    0.3413   -0.1221   -1.9077 H   0  0  0  0  0  0           0  0  0\n    0.7936    3.9450   -0.8262 H   0  0  0  0  0  0           0  0  0\n    0.9657    3.9376    0.9454 H   0  0  0  0  0  0           0  0  0\n    1.6252    1.9145    1.9264 H   0  0  0  0  0  0           0  0  0\n   -0.9158   -2.3301   -1.1841 H   0  0  0  0  0  0           0  0  0\n   -0.8447   -2.4844    0.5878 H   0  0  0  0  0  0           0  0  0\n   -1.5283   -0.2327   -2.0302 H   0  0  0  0  0  0           0  0  0\n    2.6724    5.0456   -0.1099 H   0  0  0  0  0  0           0  0  0\n   -2.6744   -3.5221   -0.3232 H   0  0  0  0  0  0           0  0  0\n  1  2  1  0     0  0\n  1  3  1  0     0  0\n  1  4  1  0     0  0\n  1 13  1  0     0  0\n  2  5  1  0     0  0\n  2  6  1  0     0  0\n  2 14  1  0     0  0\n  3  7  1  0     0  0\n  3  8  1  0     0  0\n  3 15  1  0     0  0\n  4 16  1  0     0  0\n  5  9  1  0     0  0\n  5 10  1  0     0  0\n  5 17  1  0     0  0\n  6 18  1  0     0  0\n  7 11  1  0     0  0\n  7 19  1  0     0  0\n  7 20  1  0     0  0\n  8 21  1  0     0  0\n  9 12  1  0     0  0\n  9 22  1  0     0  0\n  9 23  1  0     0  0\n 10 24  1  0     0  0\n 11 25  1  0     0  0\n 12 26  1  0     0  0\nM  END\n'},
   'image': 'iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAYAAACtWK6eAAAACXBIWXMAAAqJAAAKiQGQfKouAAACMXpUWHRtb2xTb3VyY2UAAHicpZVti5tAEMe/yrBv8qZxn3RdQ8xx9Cgt3FForrTvwsZsckJ0j9XLw7fvGHvFVKXHFRHG2d/8/7syjvObU7GHg/VV7sp0wgM2AVtmbpOXu3Ty/fHTVE9uFvMMIQTLKiVPdf08o/R4PAbZky3MyZVB5grSrs9OVX7FHGXg/I4Kxjj9+XC/vNRM87KqTZlZrKryWXVJ3rvM1M0uxixoYfwhL2mL08IfWrUV1yvOVyw4VRvy5yzkI67dYils872FrfOFqeHAdcDxlB9gZ0vrTW03sD5f0iIOGFnMH+5c9lLYssawkcgzs1/W/iXDROH2NntBNQy+3KWk4Fhgalfcem/O0ERN2nAwAowEE4KJwCgwMRgNJgHDGd64zgUBu7eN0eP52eJ2obm+Xt144RsSKWGBUiLRMlIhjyMtmILpQI4HSRKJRGmuE61kxDUMVQ5gQ2oykCJWnLFYxghrKYYMpgPYkEMYqEjKhEURlzGTAqleisAZD4t7kVpxzULFOONCozC8NddYi1AqtJdCJTKUCQwK/gf3Vt9BbiBJ6GK+duXm0kVtCPkmJWtOLj31zW4r8butCDi/sT4l/LWqRUUPlWOo7KFhB23JZW29dYsfc9p5ah+6UuG1FDZ9NOYa9VD1Xld1LYXfWTzmGvdQPeb6+R+u+loKv+tkzDXpoZy997BNZVcsbubHmDH/q2OSdtB0YdrpNPo60DDsDTvamYQUfwCLXxbmvDiWZT9lAAAI+ElEQVR42u2dMWgVSRjHAwaM4oEQRcXABbR4RfRSpLAQTkUhRYoUKVJYpLCwsAiaQrgUQS1SWFhYpFBIkYMUr7CwsBACZxFChBRBROSIYKFHihSRE33g3P733cZ9z817Jrez+835+8FwesXdx775zXzzzexshwOAbengEQAgCACCACAIAIIAIAgAggAgCACCACAIACAIAIIAIAgAggAgCACCACAIAIIAIAgAggAAggAgCACCACAIAIIAIAgAggAgCACCAACCACAIAIIAIAgAggAgCACCACAIAIIAIAgAIAgAggAgCACCACAIAIIAIAgAggAgCAAgCACCACAIAIIAIAgAggAgCACCACAIAIIAAIIAIAgAggAgCACC/O/4/Nm5iQnnjh1z7ujR+p/177aeesZj7+ggZgT5Qbh1y7mLF517+7bezp937vZt250txJgRJFBOnnTuxYuvf19drf87y50txJgRJFC6upz7+PHr3/XnffsaO1ZWI2YE+SE4cSK80TjEmBEkUKamGvP5Cxfs5/MhxowggfLpk3PXrzt35Ei9InTjhv2KUIgxIwgAggAgCACCACAItOTOnXpFKKttbNiMeXFx+5gfPUIQyJG+vuwNNW3EWUWCjI1lt2oVQSBHhoezBenv59kgCLibN7MFGR3l2SAIuPn5bEGUz1tmcNC53t5vW62GIJAjy8vZgljP5VdWnFtYaGxamzCDQK5sbmYLosN/gCDg6qlJsyDpo+QWUXxra43NalkaQQJH+XxajkrFfsya4ZrXH1pPIQjkzd/j424jEiNpH1T6BQSBOg9nZtxPkRhJ+00XIACCQJ1nz55FmVXHVpudnQ0i7mq16qampuJ27949fkgE8cP6+nqDIMsq/QbA3NycGxsbi9sdnSkDBPHFoUOHtgTZoBqEINDI2bNnYzmO6vVVQBBo5OrVq7Eggyr5BsLm5qbr7e2Nm9ZRgCDe0CJXgly7di2ouBcWFuL20frGZoLnK1MRxBNPnjyJBbl//z4Pwyeer0wNQpBarRbOiPYva2trsSAajUPi/fv37s2bN+EE7PnK1A7rYmgE3r9/vzt8+HBchgyBt9FIdvnyZdfZ2ekuXbrkXr58GUTc8/Pzrru72+3du9fdvXs3fv7m8XxlqllBnj596iqViuvr64tHYf14WjyqOmR1X0GznPYPDhw4EO8lvHr1KkqJJ6LfsCv+p9Vy78rKSvxce3p64kFIC/T+/v5oID4Zp4qm8XxlqjlBXr9+7YaHh93BgwfdzMxMwyimDqhdXnW4K1euuHfv3pmJW7vQEvjMmTPfCKwZRNUslXwfPHhgZmTWhqaeo4SenJxsSGMVo2LVfo5i1+9iEs9XppoRRCVG/Uj6sVQibTXaKoUZHR2NJZqeni61w61GI9a5c+e2Rt92C3eNygMDA6WWUfW8VGXT89Nz1HppO/Q7mJkFJWnUN1x6YPR8ZaoJQf6MOpY6mDra6g5eLFInU2crIxXQ6CuRk9FXgn9v55TU6pxap0j2ItFzUuqqFGonBYRSZ0E9W73rHz1rp7J5gQWbcgVRKhLlvnr34I9dvnuQpAL64fQD+l4QJ4UDdfCRkZFdpx5KD7VOkWBat/iu0inOoaGhOGVqTl13Klihs6BmZc0MSqNKeCuzHEGi0TdKfusjgnLIHDpHEamACgcqGqjpz3mwuLgYr1vU6R55uKRNz+FmNPrquWjTMo/nkp4FlaJ5mQU1eEbPJX5xq8T3+YsVRKOWjlFHDza+BqdF7rtbklRAI2VeqUCrwkFe6Ei8ZsGL0UiZ1yyYzKx5/jebZ0Et8iVfXrPgB60vdGGdBk+dKC55/6s4QTTi6tVTXaBWwOZZkgoo195tKqB1hUZfpUF5jb7fO9qP663EXf7/NCsla7PHjx8XkCkvx2ViVfHm/0OqrFnpl2gQ+itam7mC12blCqLcUXlkNPoWec+SHro2vHaTCqRH9NWCc9/0emEns2CyQZlU94o+fTCXKrZob8XsusaLIO3KZe0OjZVIkgpoJtA+SquOk14TVEu+yypdcWrVcZo3KMvcH1Is6XK9qn2tBoK802G7grQ7NGaAVqlA0VWlvGbB9AbloqGL3rS3oiqf4taeS7rz55VKhiVIu0NjhkhSAcmytLQUpyMSQ+mJpd35Vgvi58+fx6mM0kDLZ9S016Kqn2ZCVf58FCPsCNLq0Fe7Q2PGSFKBPXv2uFOnTpkafdvNgqdPn47j3skGZdmzoKp/GoSOHz/upZxtfwZpd2jMKEkKEBLaqOyy/L2RNrKERH6CtDs0ZjRt0TsbWkyGhErOinvNwz4S+BKk3aExgygnVkdTLh8Sqvwo7iL2OBDkB0apijqayowhoUWu4uZyNwQpJFVRa1Wvt4QW5UnMoaWGCBIYKjUmnS2kKlYSs8rUgCDeUxU1lSFDQHseScyhpYYIEhDavU3fnzsRyA3s2oFOxx1KaogggZFOVdR0ODAEdOw+HTc3ICKIF6qzs+7nqIMl7dcANjXFhUqlIe7fA0kNESQwvkSpypeog6Wb+e8I1mruS2dnY9zj4/RiBPGSq3x7rmwH7zCUgo7vNMccSGqIIKGhtxubO5v1j1bqkF9zzHpnGxAk71Ql82SyzpNZZno6O+7A7i1GEOtkpSpqIyO249a72llxW08NESQw9CptVkfThRKWGRjIjpvvmSNIIamK9XcsdBVOVtyTk/RkBMkR3cm13RuSVi9p1js228VsPTVEkABnEF1OltWsvietuLaL2XpxAUEAEAQAQQAAQbx/Ppi4ESRsPH8+mLgRJGw8fz6YuBEkbDx/Ppi4ESRsPH8+mLgRJGw8fz6YuBEkbDx/Ppi4EQQAQQAQBAAQBABBABAEAEEAEAQAQQAQBABBABAEABAEAEEAEAQAQQAQBABBABAEAEEAEAQAQQAAQQAQBABBABAEAEEAEAQAQQAQBABBAABBABAEAEEAEAQAQQAQBABBABAEAEEAEAQAEAQAQQAQBABBABAEAEEAEAQAQQAQBAAQBABBABAEAEEAEAQAQQAQBABBABAEAEEAAEEAEAQAQQAQBKAs/gEO6Zzzwf7GCgAAAABJRU5ErkJggg=='},
  {'id': '0000050817',
   'lastMod': 1653580459000,
   'summary': {'u': 'rn/eq/50-81-7',
    'na': 'Ascorbic acid [USP:INN:BAN:JAN]',
    'rn': '50-81-7',
    'ik': 'CIWBSHSKHKDKBQ-JLAZNSOCSA-N',
    'f': 'C6-H8-O6',
    'w': 176.1232,
    '3d': True,
    'mh': 'Ascorbic acid',
    'ci': 48987},
   'notes': [{'t': 211,
     'e': [{'d': 'A six carbon compound related to glucose. It is found naturally in citrus fruits and many vegetables. Ascorbic acid is an essential nutrient in human diets, and necessary to maintain connective tissue and bone. Its biologically active form, vitamin C, functions as a reducing agent and coenzyme in several metabolic pathways. Vitamin C is considered an antioxidant.',
       's': ['MeSH']}]}],
   'categories': [{'t': 386,
     'e': [{'d': 'Acidifier (Urinary)', 's': ['USPDDN']},
      {'d': 'Antioxidants', 's': ['MeSH', 'SIS']},
      {'d': 'Antiviral (COVID-19)', 's': ['ClinicalTrials.gov', 'PubChem']},
      {'d': 'Drug / Therapeutic Agent', 's': ['RTECS']},
      {'d': 'Growth Substances', 's': ['SIS']},
      {'d': 'Human Data', 's': ['RTECS']},
      {'d': 'Micronutrients', 's': ['SIS']},
      {'d': 'Mutation Data', 's': ['RTECS']},
      {'d': 'Protective Agents', 's': ['SIS']},
      {'d': 'Reproductive Effect', 's': ['RTECS']},
      {'d': 'Tumor Data', 's': ['RTECS']},
      {'d': 'Vitamin (Antiscorbutic)', 's': ['USPDDN']},
      {'d': 'Vitamins', 's': ['MeSH', 'SIS']}]}],
   'numbers': [{'t': 261, 'e': [{'d': '50-81-7', 's': ['PubMed Toxicology']}]},
    {'t': 102, 'e': [{'d': 'PQ6CK8PD0R', 's': ['FDA SRS']}]},
    {'t': 610,
     'e': [{'d': '1018124-03-2', 's': ['TSCAINV']},
      {'d': '1129294-89-8', 's': ['TSCAINV']},
      {'d': '129940-97-2', 's': ['RTECS']},
      {'d': '1428525-25-0', 's': ['TSCAINV']},
      {'d': '14536-17-5', 's': ['GRAS', 'RTECS']},
      {'d': '154170-90-8', 's': ['TSCAINV']},
      {'d': '1703051-92-6', 's': ['TSCAINV']},
      {'d': '259133-78-3', 's': ['TSCAINV']},
      {'d': '30208-61-8', 's': ['RTECS']},
      {'d': '50976-75-5', 's': ['RTECS']},
      {'d': '56172-55-5', 's': ['NLM']},
      {'d': '56533-05-2', 's': ['RTECS']},
      {'d': '57304-74-2', 's': ['RTECS']},
      {'d': '57606-40-3', 's': ['RTECS']},
      {'d': '623158-95-2', 's': ['TSCAINV']},
      {'d': '882690-91-7', 's': ['TSCAINV']},
      {'d': '884381-69-5', 's': ['TSCAINV']},
      {'d': '885512-24-3', 's': ['TSCAINV']},
      {'d': '88845-26-5', 's': ['TSCAINV']},
      {'d': '896436-13-8', 's': ['TSCAINV']},
      {'d': '89924-69-6', 's': ['RTECS']}]},

In [47]:
base_url = 'https://chem.nlm.nih.gov/api/data/name/inlist'
data = 'complete'
out_format = 'tsv'  # tsv json
api_url = f"{base_url}/{compound_str}?data={data}&format={out_format}"
response = requests.get(api_url)

In [48]:
def to_df(result):
    return pd.read_table(io.StringIO(result))

In [49]:
df = to_df(response.text)
df.columns

Index(['RN / ID', 'Last Modified', 'Name', 'InChIKey', 'Formula', 'Weight',
       'Has 3D', 'MeSH', 'Citations', 'InChI', 'SMILES', 'Type', 'Type ID',
       'Data', 'Sources', 'URL', 'Tox Organism', 'Tox Test Type', 'Tox Route',
       'Tox Dose', 'Tox Effects', 'Tox PubMed ID', 'PP Property', 'PP Data',
       'PP Value', 'PP Units', 'PP Temperature', 'PP Source'],
      dtype='object')

In [50]:
df

,RN / ID,Last Modified,Name,InChIKey,Formula,Weight,Has 3D,MeSH,Citations,InChI,...,Tox Route,Tox Dose,Tox Effects,Tox PubMed ID,PP Property,PP Data,PP Value,PP Units,PP Temperature,PP Source
0,50-70-4,2022-09-22 18:27:55,Sorbitol [USP:NF],FBPFZTCFMRRESA-JGWLITMVSA-N,C6-H14-O6,182.171,Y,Sorbitol,20337.0,InChI=1S/C6H14O6/c7-1-3(9)5(11)6(12)4(10)2-8/h...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,50-70-4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,50-70-4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,50-70-4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,50-70-4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2766,9002-18-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2767,9002-18-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,oral,6100.0 mg/kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2768,9002-18-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,oral,16.0 gm/kg (16000.0 mg/kg),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2769,9002-18-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,oral,5800.0 mg/kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2770,9002-18-0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,oral,11.0 gm/kg (11000.0 mg/kg),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
short_compound_list = 'glucose'
base_url = 'https://chem.nlm.nih.gov/api/data/name/inlist'
data = 'complete'
out_format = 'tsv'  # tsv json
api_url = f"{base_url}/{short_compound_list}?data={data}&format={out_format}"
response = requests.get(api_url)
df = to_df(response.text)
df

,RN / ID,Last Modified,Name,InChIKey,Formula,Weight,Has 3D,MeSH,Citations,InChI,...,Tox Route,Tox Dose,Tox Effects,Tox PubMed ID,PP Property,PP Data,PP Value,PP Units,PP Temperature,PP Source
0,50-99-7,2021-09-10 15:53:34,Glucose [JAN],GZCGUPFRVQAUEE-SLPGGIOYSA-N,C6-H12-O6,180.1548,Y,Glucose,466064.0,InChI=1S/C6H12O6/c7-1-3(9)5(11)6(12)4(10)2-8/h...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,50-99-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,50-99-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,50-99-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,50-99-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,50-99-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,log P (octanol-water),-3.240000e+00,NaN,NaN,NaN,EXP
124,50-99-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Water Solubility,1.200000e+06,NaN,mg/L,30.0,EXP
125,50-99-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Vapor Pressure,1.820000e-08,NaN,mm Hg,25.0,EST
126,50-99-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Henry's Law Constant,5.880000e-11,NaN,atm-m3/mole,25.0,EST
127,50-99-7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Atmospheric OH Rate Constant,1.040000e-10,NaN,cm3/molecule-sec,25.0,EST

In [57]:
df.to_csv('CHEMID_glucose.csv')